
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: review-site
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2048Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20480Mi