apiVersion: v1
kind: Service
metadata:
  name: gerrit-headless
  labels:
    app: gerrit
spec:
  selector:
    app: gerrit
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: gerrit-postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: db
    targetPort: db
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: gerrit-frontend
  labels:
    app: gerrit
spec:
  ports:
  - port: 80
    name: web
    targetPort: web
  - port: 29418
    name: ssh
    targetPort: ssh
  selector:
    app: gerrit
  type: LoadBalancer